### ISSUE TITLE
Incorrect expiry times

### ISSUE THREAD

**Issue by 5j9** [thewh1teagle/rookie#7]
Consider the following python script (using v0.2.7):
```python
import browser_cookie3, rookiepy

print('browser_cookie3:')
for c in browser_cookie3.firefox(domain_name='test.wikipedia.org'):
    print(c.name, c.expires)

print('\nrookiepy:')
for c in rookiepy.firefox(['test.wikipedia.org']):
    print(c.name, c.expires)

```

prints the following:
```
browser_cookie3:
testwikiss0-UserID 1728238484
testwikiUserID 1728238484
testwikiss0-UserName 1728238484
testwikiUserName 1728238484
WMF-Last-Access 1699444800
WMF-DP 1696723200
NetworkProbeLimit 1696706087
testwikiSession None
ss0-testwikiSession None
testwikimwuser-sessionId None

rookiepy:
testwikiss0-UserID 1728238484000
testwikiUserID 1728238484000
testwikiss0-UserName 1728238484000
testwikiUserName 1728238484000
WMF-Last-Access 1699444800000
WMF-DP 1696723200000
NetworkProbeLimit 1696706087000
testwikiSession 2012062492654
ss0-testwikiSession 2012062492654
testwikimwuser-sessionId 2012062492654
```

Note that expiry values returned by rookiepy are 1000 times greater than the ones in browser_cookie3. (they are in milliseconds instead of the expected seconds)

Also, for the last three items, rookiepy has returned `2012062492654` instead of `None`. This currently does not cause issue, because it is in milliseconds, but if we convert values to second then the cookie is expired.

**Comment by thewh1teagle** [comment]
Thanks for letting me know. 
It's hard to test it because I develop for multiple platforms and browsers, I will check that soon and update, 
As a temporarily solution, if you use it as cookiejar with requests, just iterate the cookies in cookiejar and set the expires to None
And important thing: 
To check if cookies presented in the request you should prevent request redirect by passing allow_redirect=False to requests methods

**Comment by thewh1teagle** [comment]
Fixed in latest version.

**Comment by 5j9** [comment]
Confirmed. Thank you!
